package com.theelitedevelopers.bunkies.core.utils;

public class Constants {
    public static final String RECEIVER_UID = "receiver_uid";
    public static final String PREFERENCES_DONE = "preferences_done";
    public static final String PERSONAL_TRAITS_DONE = "personal_traits_done";
    public static final String PERSONAL_INTERESTS_DONE = "personal_interests_done";
    public static final String PERSONAL_HABITS_DONE = "personal_habits_done";
    public static final String LIVING_HABITS_DONE = "living_habits_done";
    public static final String LIVING_CHOICES_DONE = "living_choices_done";
    public static final String SETUP_PROFILE_DONE = "setup_profile_done";
    public static final String HABIT_CLEAN_FREAK = "habit_clean_freak";
    public static final String HABIT_PARTY_ANIMAL = "habit_party_animal";
    public static final String HABIT_PETS = "habit_pet";
    public static final String HABIT_SMOKING = "habit_smoking";
    public static final String HABIT_LOTS_OF_GUESTS = "habit_lots_of_guests";
    public static final String LIVING_HABIT_CLEAN_ROOM = "living_habit_clean_room";
    public static final String LIVING_HABIT_HAVE_VISITORS = "living_habit_have_visitors";
    public static final String LIVING_HABIT_STAY_HOW_LONG = "living_habit_stay_how_long";
    public static final String LIVING_HABIT_SMOKING_ACCEPTABLE = "living_habit_smoking_acceptable";
    public static final String LIVING_HABIT_FOOD_CHOICE = "living_habit_food_choice";
    public static final String LIVING_CHOICE_RENT_START = "living_choice_rent_start";
    public static final String LIVING_CHOICE_RENT_END = "living_choice_rent_end";
    public static final String LIVING_CHOICE_LOOKING_FOR = "living_choice_looking_for";
    public static final String LIVING_CHOICE_PETS = "living_choice_pets";
    public static final String LIVING_CHOICE_SHARE_TOILET = "living_choice_share_toilet";
    public static final String ROOMMATES = "roommates";
    public static String NAME = "name";
    public static String EMAIL = "email";
    public static String DATE_OF_BIRTH = "date_of_birth";
    public static final String GENDER = "Gender";
    public static final String CITY = "City";
    public static final String NEIGHBOURHOOD = "Neighbourhood";
    public static final String OCCUPATION = "Occupation";
    public static final String BIO = "bio";
    public static String UID = "uid";
    public static String ID = "id";
    public static String HAS_BEEN_LAUNCHED = "has_been_launched";
    public static final String TOKEN = "token";
}
